#!/bin/sh

my_maildir=$(realpath "${MAILDIR:-${HOME}/Mail}")

my_taskrc=$(realpath "${TASKRC:-${HOME}/.taskrc}")
my_taskdir=$(realpath "${TASK_DIR:-${HOME}/.task}")

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"

my_afew_config=$(realpath "${XDG_CONFIG_HOME}/afew")
my_neomutt_config=$(realpath "${XDG_CONFIG_HOME}/neomutt")
my_notmuch_config=$(realpath "${HOME}/.notmuch-config")


docker run --rm -ti \
            -e USER_ID=$(id -u) \
            -e GROUP_ID=$(id -g) \
            --mount type=bind,src="${HOME}",dst=/home/user,consistency=default \
            --mount type=bind,src="${my_maildir}",dst=/home/user/Mail,consistency=default \
  mailenv


